### ISSUE TITLE
Sensor Name

### ISSUE THREAD

**Issue by dridas** [AlbertWeichselbraun/humidity-probe-influxdb#3]
I haven't set this up yet - I have 8266's, but have 3 ESP32's and 3 BME280's that should be delivered today.  With that said, how can I modify the sensor names, in order to differentiate the sensors in the influxdb?

**Comment by AlbertWeichselbraun** [comment]
The sensor data is tagged with the sensors i2c address _and_ the host's mac address which allows differentiating between hosts and sensors.

In case this isn't sufficient for your use case, you can also add additional metadata by modifying lines 237 and 240 of `humidity-probe-influxdb.ino`.
